#!/usr/local/bin/php
<?php

$db_name = "xxxxx";
$db_url = "db.lib.utexas.edu";
$u = "regdbuser";
$p = "regdbuser";

$connection = @mysql_connect("$db_url","$u","$p") or die ("Couldn't main connect.");
$db = @mysql_select_db($db_name, $connection) or die("Couldn't select database."
);
for ($x=0; $x<30; $x++){
	$sql = "
 	SELECT title_text, work.work_id
        FROM title, `work`
        WHERE title.work_id = work.work_id
        AND title_refinement is null       
 	";
 	$this_result = @mysql_query($sql,$connection) or die("Couldn't execute query.");
	while ($row = mysql_fetch_array($this_result)) {
	$title_text = $row['title_text'];
	$work_id = $row['work_id'];
	$title_text = addslashes($title_text);
	$sql2 = "
 	UPDATE
        `work`
        SET 
        work_title = '$title_text' 
 	WHERE work_id =	$work_id
 	";
 	$result = @mysql_query($sql2,$connection) or die("Couldn't execute query on work $work_id.");

}	}

	?>

